### ISSUE TITLE
Youtube video link doens't exist

### ISSUE THREAD

**Issue by Esperadoce** [dotnet-presentations/dotnet-maui-workshop#107]
[full 4-hour walkthrough](https://www.youtube.com/DuNLR_NJv8U)
it's seems like thre's an error on the link.

Can you please update it to the right video ?

**Comment by jamesmontemagno** [comment]
Here you go - https://www.youtube.com/watch?v=DuNLR_NJv8U

**Comment by Esperadoce** [comment]
thank you
