### ISSUE TITLE
Where can I find real MAUI Unit Test sample?

### ISSUE THREAD

**Issue by AlexNek** [dotnet-presentations/dotnet-maui-workshop#118]
I can find a lot of suggestions for using additional .net x.0 platform like: https://github.com/jfversluis/MauixUnitTestSample.
But I have additional MAUI dll with platform specific implementation and this suggestion can not work, so I can create MAUI library as unit test and resharper could select platform dependent build but can not run it.
What is  Microsoft recommendation for creation MAUI Unit tests?

Here is nothing about project configuration
https://learn.microsoft.com/en-us/dotnet/architecture/maui/unit-testing

**Comment by jamesmontemagno** [comment]
Have you looked at the sample here: https://github.com/dotnet-architecture/eshop-mobile-client ?
