### ISSUE TITLE
URL for raw json not working

### ISSUE THREAD

**Issue by iSukhi** [dotnet-presentations/dotnet-maui-workshop#120]
I am trying to access the mentioned URL in readme.md but the URL is not working.
Because of this, the Monkey images are not loading. 

The URL is as follows : 
https://raw.githubusercontent.com/jamesmontemagno/app-monkeys/master/MonkeysApp/monkeydata.json

**Comment by jamesmontemagno** [comment]
This is loading fine for me....


Unless for some reason your are on a VPN or is blocked or something....
