### ISSUE TITLE
Details Page Border Issue

### ISSUE THREAD

**Issue by wbaldoumas** [dotnet-presentations/dotnet-maui-workshop#124]
## Description

In the latter modules, when working on the monkey details page, the border around the monkey's image is cut off due to not requesting enough width.

## Expected Behaviour

The border around the monkey's image should not be cut off, like this:

![fix](https://github.com/dotnet-presentations/dotnet-maui-workshop/assets/45316999/22a47b37-1c1d-4f09-b287-2cc8c184d54d)

## Actual Behaviour

The border around the monkey's image is cut off, like this:

![current](https://github.com/dotnet-presentations/dotnet-maui-workshop/assets/45316999/45fcd294-1c36-4658-858f-619aea9911ed)

## Steps to Reproduce

1. Run one of the latter modules that include the monkey details page.
2. Load monkeys.
3. Navigate to the details page for a monkey and view the issue.

**Comment by jamesmontemagno** [comment]
thanks for the PR!
