### ISSUE TITLE
Getting error running displaying data solution 

### ISSUE THREAD

**Issue by akoranteng** [dotnet-presentations/dotnet-maui-workshop#131]
I have downloaded the latest solution for the workshop from the GitHub page. When I run  the Displaying Data project, I am getting  
Nuget Package re\store errors. IN the package Manager console window:

Getting restore information for project /Users/alexkoranteng/Downloads/dotnet-maui-workshop-main-2 latest/Part 1 - Displaying Data/MonkeyFinder/MonkeyFinder.csproj
/usr/local/share/dotnet/sdk/7.0.315/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5) : error NETSDK1147: To build this project, the following workloads must be installed: maui-tizen
To install these workloads, run the following command: dotnet workload restore
Unable to create package spec for project. '/Users/alexkoranteng/Downloads/dotnet-maui-workshop-main-2 latest/Part 1 - Displaying Data/MonkeyFinder/MonkeyFinder.csproj'

In your Github page, it mentions that: I should right click on the solution to restore Nuget packages but the restore.n Nuget Package cannot be found here. Can you v verify from your end and Advise, so that I can ran the sample

**Comment by jamesmontemagno** [comment]
Looks like you dont' have .NET 8 installed, please install the latest release: https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?view=net-maui-8.0&tabs=vswin

**Comment by akoranteng** [comment]
James,

Thanks for the response and link: I followed through with it and it looks to download .Net 8.0, I will need a subscription to Apple developer program for a yearly charge of $98.00  as one of the requirements. I am aware of the need for the latest version of Xcode download.
I used to be able run .Net MAUI apps from your video tutorial series without this requirement for the developer program. It looks like there has a been a workflow requirement change.

Can you kindly confirm figuring you are the guru of this stuff can I suggest the docs to be updated for better experience for the community.

See the text I copied form the developer support page.

To use Xcode Cloud, you’ll need Xcode 13.4.1<https://developer.apple.com/xcode/> or later and membership in the Apple Developer Program. Get started by configuring a workflow in Xcode. This can be done by the Account Holder, an Admin, or an App Manager. It can also be done by a team member with the Developer or Marketing role who has been given access to create app records in App Store Connect. Learn more about roles<https://developer.apple.com/support/roles/>. You’ll get 25 compute hours per month for free.To use Xcode Cloud, you’ll need Xcode 13.4.1<https://developer.apple.com/xcode/> or later and membership in the Apple Developer Program. Get started by configuring a workflow in Xcode. This can be done by the Account Holder, an Admin, or an App Manager. It can also be done by a team member with the Developer or Marketing role who has been given access to create app records in App Store Connect. Learn more about roles<https://developer.apple.com/support/roles/>. You’ll get 25 compute hours per month for free.

Regards

Alex. Koranteng


On May 10, 2024, at 12:28 PM, James Montemagno ***@***.***> wrote:



Looks like you dont' have .NET 8 installed, please install the latest release: https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?view=net-maui-8.0&tabs=vswin

**Comment by jamesmontemagno** [comment]
You only need a developer account for iOS development to put it on a device, not on a simulator. So go down this route.

else run on Android, Windows, Mac
