### ISSUE TITLE
Feedback: Re-order editing to enable hot-reload demos 

### ISSUE THREAD

**Issue by csharpfritz** [dotnet-presentations/dotnet-maui-workshop#26]
In part 2, if we move the step to register services above the XAML modifications, XAML hot reload will allow students to immediately see the updates to the UI.

Otherwise, students need to wait because dependency injection for the new MonkeyViewModel and MonkeyService are not available

**Comment by csharpfritz** [comment]
Also from live workshop - add the button to fetch the monkeys earlier so that we can see the Grid layout as well as give a way to fetch the data to be formatted in the CollectionView.

**Comment by csharpfritz** [comment]
There's a similar issue with part 3 -- the route for the Details page and services for it are registered at the end of the module.

Let's consider moving those steps higher in the lesson.

**Comment by jamesmontemagno** [comment]
fixed up :)
