### ISSUE TITLE
Android issues in RC1

### ISSUE THREAD

**Issue by evilz** [dotnet-presentations/dotnet-maui-workshop#35]
Emulator Pixel 5

- Images are not displayed 
- CollectionView_SelectionChanged is not call on click
- CollectionView.EmptyView still displayed after Monkeys binding is loaded

Same code works on Windows (11)

**Comment by jamesmontemagno** [comment]
Yes right now on Android there is a bug with EmptyView as I noted.

Can you put your output when loading the items in a gist.github.com for me as there may be some ssl issues with the emulator loading some image data perhaps.

I haven't seen the click issue at all, but ill double check.

**Comment by evilz** [comment]
I got the same on Device.
Emulator and device is running exact same.

No image, I can give a try without https. 
For detail view, I can navigate if I click on the border or near it.

**Comment by jamesmontemagno** [comment]
Could be a change in the RC.... let me give that a test and maybe file a big.

No images is weird though... but I'll boot it up here in a few. Thanks for the feedback.

**Comment by jamesmontemagno** [comment]
@PureWeen I could move to a tap gesture recognizer perhaps instead of selection changes... but thoughts?

**Comment by PureWeen** [comment]
> @PureWeen I could move to a tap gesture recognizer perhaps instead of selection changes... but thoughts?

Probably related to this
https://github.com/dotnet/maui/issues/6075

**Comment by evilz** [comment]
@jamesmontemagno For image here some logs =>

```
[Glide] Load failed for https://via.placeholder.com/150 with size [344x344]
[Glide] class com.bumptech.glide.load.engine.GlideException: Failed to load resource
[Glide] There was 1 root cause:
[Glide] com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: 410)
[Glide]  call GlideException#logRootCauses(String) for more detail
[Glide]   Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
[Glide] There was 1 root cause:
[Glide] com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: 410)
[Glide]  call GlideException#logRootCauses(String) for more detail
[Glide]     Cause (1 of 1): class com.bumptech.glide.load.HttpException: Failed to connect or obtain data, status code: 410
[Glide]   Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{StringUri->Object->Drawable}, LOCAL
[Glide]     Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{StringUri->Drawable->Drawable}
[Glide]     Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{StringUri->Bitmap->Drawable}
[Glide] Root cause (1 of 1)
[Glide] com.bumptech.glide.load.HttpException: Failed to connect or obtain data, status code: 410
[Glide] 	at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:98)
[Glide] 	at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:58)
[Glide] 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
[Glide] 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
[Glide] 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
[Glide] 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
[Glide] 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
[Glide] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[Glide] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[Glide] 	at java.lang.Thread.run(Thread.java:920)
[Glide] 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
[Glide] Caused by: java.io.FileNotFoundException: https://via.placeholder.com/150
[Glide] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
[Glide] 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
[Glide] 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
[Glide] 	at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:95)
[Glide] 	... 10 more
[Glide] Load failed for https://via.placeholder.com/150 with size [344x344]
[Glide] class com.bumptech.glide.load.engine.GlideException: Failed to load resource
[Glide] There was 1 root cause:
[Glide] com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: 410)
[Glide]  call GlideException#logRootCauses(String) for more detail
[Glide]   Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
[Glide] There was 1 root cause:
[Glide] com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: 410)
[Glide]  call GlideException#logRootCauses(String) for more detail
[Glide]     Cause (1 of 1): class com.bumptech.glide.load.HttpException: Failed to connect or obtain data, status code: 410
[Glide]   Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{StringUri->Object->Drawable}, LOCAL
[Glide]     Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{StringUri->Drawable->Drawable}
[Glide]     Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{StringUri->Bitmap->Drawable}
[Glide] Root cause (1 of 1)
```

**Comment by jamesmontemagno** [comment]
@jonathanpeppers is this something you can look at... it was working previously...

**Comment by jonathanpeppers** [comment]
HTTP 410 is "gone". What URL was used for the image? The app also has the internet permission?

**Comment by evilz** [comment]
I'm able to run this code 
```
httpClient.GetAsync("https://www.montemagno.com/monkeys.json");
```
And manifest got this line

```
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

So network looks OK.

And url of image is this one => https://via.placeholder.com/150

**Comment by jamesmontemagno** [comment]
@jonathanpeppers that seems very odd that we require that for images..... Should this be in the templates then? I will add it to the projects here, but that seems odd IMHO

**Comment by jamesmontemagno** [comment]
Does Glide need the internet permission manually in there?
```
<uses-permission android:name="android.permission.INTERNET"/>
```

**Comment by jonathanpeppers** [comment]
It's downloading a picture, so you need the internet?

**Comment by jonathanpeppers** [comment]
Debug builds we add the internet permission automatically, is that the confusion? Otherwise debugging wouldn't work.

**Comment by jamesmontemagno** [comment]
hmmmmmmmmm yeah... i guess that is what is odd... like our templates should probably have the internet permission in it by default if it doesn't already.

They were debugging it which is why they were able to download the json file.... but the images don't load... so unless it was release.

That temp image they listed is from glide, not from me... You shoudl be able to pull down and run the final folder to see it in action.... hmmmm

**Comment by jamesmontemagno** [comment]
Alright... looks like image loading is a bug in RC1:

https://github.com/dotnet/maui/issues/6067

when updating to latest Glide version

**Comment by jamesmontemagno** [comment]
Also linking to https://github.com/dotnet/maui/issues/6119 for the empty view

**Comment by jbaynhamuk** [comment]
In addition to not seeing the images on the Android emulator, I also can't click through from the monkeys on the MainPage to see the detail. This works on Windows, but on Android if I set a  breakpoint in CollectionView_SelectionChanged in the code behind it never gets hit.

**Comment by jbaynhamuk** [comment]
I also, in Android, when doing nothing in particular, occasionally get 
"System.InvalidOperationException
  Message=An attempt was made to transition a task to a final state when it had already completed."

**Comment by jamesmontemagno** [comment]
I would maybe post this over to https://github.com/dotnet/maui as that seems like something new @jbaynhamuk

**Comment by jbaynhamuk** [comment]
I have seen if I can recreate the issue using your code from Part 6, and I can't, so perhaps I have an error somewhere from typing along with your lessons.

I still can't click through on a monkey to the details unless I click in the margin either side of the monkey, but not on the lozenge for the monkey itself!

**Comment by jamesmontemagno** [comment]
For the click issue we are tracking here: https://github.com/dotnet/maui/issues/6075 @PureWeen do you think I should just changed to a tapgesture or will this be fixed up in rc2?

**Comment by llssprattt** [comment]
good afternoon. I was wondering if the issue with pictures showing up in android is resolved?

**Comment by jamesmontemagno** [comment]
It is resolved in the next RC from looking at the ticket

**Comment by gizmohd** [comment]
When is the expected release date for that? do we know?

**Comment by jamesmontemagno** [comment]
I have updated the workshop to use tapgesture recognizers instead of selection changed to work around collectionview issue on android.


Images still not loading on RC2, but maybe RC3

**Comment by jamesmontemagno** [comment]
Tracking RequestBuilder crash https://github.com/dotnet/maui/issues/6518

**Comment by kajzik** [comment]
CollectionView_SelectionChanged works if you change Frame to Border, but deselecting an item after GoToAsync (...) does not work only if it is before.

**Comment by jamesmontemagno** [comment]
Also tracking empty view: https://github.com/dotnet/maui/issues/6119
