### ISSUE TITLE
Part 0 Assets Folder Missing/Changed to Raw

### ISSUE THREAD

**Issue by corykroll** [dotnet-presentations/dotnet-maui-workshop#43]
In the Part 0 - Overview\README.md
It mentions code:

`<!-- Assets -->`
`<MauiAsset Include="Resources\Assets\*" />`

However in the actual code going into Part 1 it looks to be

`<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->`
`<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />`

An Assets folder doesn't exist.

**Comment by jamesmontemagno** [comment]
fixed
