### ISSUE TITLE
Part 1 Monkey Display Not Matching Example

### ISSUE THREAD

**Issue by corykroll** [dotnet-presentations/dotnet-maui-workshop#44]
Ran through the Part 1 Example.  Ran the program in Windows and in Android.

The example shows the output should appear like this:
![Ideal Monkeys](https://user-images.githubusercontent.com/8052673/167050132-7118b9dc-3ef7-4072-ab69-424b5f307c52.png)

However Android showed up like this:
![Android Monkeys](https://user-images.githubusercontent.com/8052673/167050149-eb3f4358-2298-48a1-929e-11fb1776585b.png)
Monkey heading appeared, monkey text appeared but monkeys did not

Windows showed up like this:
![Windows Monkeys](https://user-images.githubusercontent.com/8052673/167050164-9a4dabf8-b0bb-4ca6-a9f5-0f834b5ec327.png)
Monkey heading appeared, pictures of monkeys appeared, but text did not

**Comment by psx1lin** [comment]
Android  can't  show  Monkey heading ..

**Comment by corykroll** [comment]
@psx1lin Maybe I'm calling it the wrong term - but in my screenshots 'Monkeys' appear at the top (with a yellow background on Android and a black background on Windows for some reason)

**Comment by jamesmontemagno** [comment]
This should now be fixed in RC3
