### ISSUE TITLE
Part 2 Android No Pictures/List Scrolling Error

### ISSUE THREAD

**Issue by corykroll** [dotnet-presentations/dotnet-maui-workshop#45]
When running through Part 2 the Windows version ran fine.
However, on Android no monkey pictures appeared.
![Part 2 Monkey List Android](https://user-images.githubusercontent.com/8052673/167062238-c9b68d4b-8bbd-4b01-a93f-4cfd4581530e.png)

Additionally, I get an odd error if I scroll to the very bottom of the list, then to the very top of the list.

System.InvalidOperationException
  Message=An attempt was made to transition a task to a final state when it had already completed.
  
I opened up the Part 3 code to verify that this was in fact an issue with the code and not something I did following along with Part 2

**Comment by jamesmontemagno** [comment]
Now fixed in RC3
