### ISSUE TITLE
Title on Detail page and Main Page never update after the first time a detail page is shown (Part 3)

### ISSUE THREAD

**Issue by polygonsheep** [dotnet-presentations/dotnet-maui-workshop#50]
On Mac desktop build and iphone simulator
MAUI RC3
Mac VS 2022 RC2

After part 3

Once you select a monkey and see its detail page the title is set to that monkey. 
Going back to main list does not update title (should go back to "Monkey Finder" but keeps monkey name). 
Selecting a new (different) monkey does not update title on detail page (still shows original monkey's name).

**Comment by polygonsheep** [comment]
Confirmed MAUI RC3, still happening

**Comment by jamesmontemagno** [comment]
I think it is this one -> https://github.com/dotnet/maui/issues/6582

**Comment by polygonsheep** [comment]
Yes, that is what I'm seeing. Thanks.
