### ISSUE TITLE
CommunityToolkit.Mvvm NuGet package reference is missing in the project available in the Finish folder (main branch)

### ISSUE THREAD

**Issue by egvijayanand** [dotnet-presentations/dotnet-maui-workshop#56]
Cloned the repository and opened the solution available in the Finish folder (main branch).

Ended up with errors when compiled, upon analysis found that the `CommunityToolkit.Mvvm` NuGet package reference is missing in the project file causing the issues.

_In fact, it's not added as a reference in any of the projects available in other folders._

Notify to @jamesmontemagno @jfversluis

**Comment by jamesmontemagno** [comment]
It is added in the Diretory.build.targets.

https://github.com/dotnet-presentations/dotnet-maui-workshop/blob/main/Directory.build.targets this is found in the Solution Items when you open it in visual studio 2022

**Comment by egvijayanand** [comment]
Detailed screenshot. Only the Properties Explorer reveals that the files are not physically present.

<img width="959" alt="VS2022-Missing-Solution-Items-2" src="https://user-images.githubusercontent.com/81947404/170708427-986d24a8-9d40-4b33-99c0-d6e9e091d2a2.png">

**Comment by jamesmontemagno** [comment]
Those files are up a level in the root.

**Comment by egvijayanand** [comment]
Yeah, copied those files.

If VS reported missing solution items, then would've checked for them.

The icons representation is quite misleading.

Have reported it to VS team.

Thanks for the response.
