### ISSUE TITLE
After .NET 7 Preview 4 all references are broken

### ISSUE THREAD

**Issue by ylr-research** [dotnet-presentations/dotnet-maui-workshop#60]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/63487874/170605068-cbc24594-ab31-4cef-adbb-a95cceddba42.png">

**Comment by jamesmontemagno** [comment]
Try it with the latest pinning that was fixed up by a community member.

https://github.com/dotnet/maui/wiki/.NET-7-and-.NET-MAUI

**Comment by ylr-research** [comment]
Thanks @jamesmontemagno. For some reason the closing comment was not posted. I mentioned #54 fixed it.
