### ISSUE TITLE
RelativeSource ViewModel not found

### ISSUE THREAD

**Issue by CiarogSoftware** [dotnet-presentations/dotnet-maui-workshop#61]
https://github.com/dotnet-presentations/dotnet-maui-workshop/blob/d9ac3fd52c81d579e32d5dcdb23bf6d8d37153ee/Part%204%20-%20Platform%20Features/MonkeyFinder/View/MainPage.xaml#L25

The MonkeysViewModel is not found in the viewmodel namespace when accessing through RelativeSource binding.

Using VS2022 Enterprise 17.3.0 Preview 1.1

![image](https://user-images.githubusercontent.com/7656133/170658664-152bf9c0-2965-4acd-8f2e-c70492363336.png)

**Comment by CiarogSoftware** [comment]
I think this may be a VS issue though. I created a new minimal project just to test this and it's the same issue. The command works just fine, but the ViewModel doesn't appear in intellisense.

**Comment by jamesmontemagno** [comment]
Yes, this looks to be an issue with IntelliSense for some reason. You should be able to continue on. Worth reporting to the team via the top right report a problem.

Sometimes I have seen this issue when debugging basically, but when i stop it is fine.

**Comment by CiarogSoftware** [comment]
[Originally reported in Xamarin in 2019](https://github.com/xamarin/Xamarin.Forms/issues/8680)

[Logged in MAUI May 2022](https://github.com/dotnet/maui/issues/7608)
