### ISSUE TITLE
IsBusy in Part-2 not working

### ISSUE THREAD

**Issue by eddylai** [dotnet-presentations/dotnet-maui-workshop#72]
tried to double click the "Get Monkeys" twice (or even more continues click)
the GetMonkeysAsync() task run multiple times
(tested on Windows Machine and Android Pixel 3xa phone the same result)

Visual Studio Community 2022 (64-bit) - Preview Version 17.3.0 Preview 2.0

**Comment by yj320696** [comment]
Same here.
If monkey service loads monkeys from internet, "Get Monkeys" button won't turn to "enabled".
But if monkeys come from cache, "Get Monkeys" works properly.
That's why @eddylai must click "Get Monkeys" button twice.

**Comment by jamesmontemagno** [comment]
This should all work now, for GetMonkeysAsync we check for IsBusy so that would lock it down.
