### ISSUE TITLE
Error DEP0700 on Windows 11

### ISSUE THREAD

**Issue by DavidRedRock** [dotnet-presentations/dotnet-maui-workshop#74]
When deploying the solution, the error will occur as shown below:

"Severity	Code	Description	Project	File	Line	Suppression State Error DEP0700: Registration of the app failed. [0x80073CFD] Windows cannot deploy to path AppX of file system type exFAT.	MonkeyFinder	"

Any solutions to fix it? Thanks.

The dev system information:

.NET SDK (reflecting any global.json):
 Version:   6.0.400-preview.22301.10
 Commit:    25580ffe7a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400-preview.22301.10\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.400-preview.22301.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jamesmontemagno** [comment]
https://docs.microsoft.com/en-us/answers/questions/642938/dep0700-registration-of-the-app-failed-0x80073cfd.html has the answer here, your install drive must be NTFS

**Comment by DavidRedRock** [comment]
Many Thanks for your advice James.
Yes, that issue has been figured out and fixed!

That issue was caused by my mess dev enviroments C: drive is NTFS and D: drive was exFAT.

It was working well when initially cloned yours on C: drive, but due to the C: space issues, the whole solutions were moved to D: and then the errors occured  after that -(: .

Now the D: file system has been changed to NTFS and the solutions are working now as well.
Thanks again!
