### ISSUE TITLE
Part 1 Monkey Display not working with android emulator 

### ISSUE THREAD

**Issue by alidvlp** [dotnet-presentations/dotnet-maui-workshop#76]
**When I run the project in its default situation, I get the following error (As shown in the attached picture)**

![Capture](https://user-images.githubusercontent.com/97786481/179432268-986b7cf8-3549-499e-a5bd-f1c39f357e91.PNG)

**Comment by jamesmontemagno** [comment]
It looks like a file path issue. Can you put it in a shorter path such as "C:\Code"
