### ISSUE TITLE
Binding Natives Android Libraries MAUI .NET

### ISSUE THREAD

**Issue by Turel1993** [dotnet-presentations/dotnet-maui-workshop#82]
Hello James, Lately I have been some problems trying to make a binding for 2 android libraries, ones I need to use in my project.
i'ved was trying multiples solutions, but any works for my project. This libraries are used for card reader application named CLIP. this libraries consists in an SDK for Android Studio developers 

this [link](https://developer.clip.mx/reference/configurar-el-ambiente-de-desarrollo) has the information for android studio pourpose.

the libraries are 

            implementation 'com.payclip.sdk:payment-ui:2.3.0'
            implementation 'com.payclip.sdk:plus-reader:1.3.0'

my best approximation is described below

1) downloades aar files
![image](https://user-images.githubusercontent.com/44584844/183519490-11ea71b0-2037-4440-994b-65a7f5800aa8.png)

2) on visual s tudio 2019 i created a project for each one
![image](https://user-images.githubusercontent.com/44584844/183519797-76a38eb3-d278-4df3-a255-dd039873f812.png)
![image](https://user-images.githubusercontent.com/44584844/183519905-f56ce022-3fe1-44ce-a553-3d29d88b4e9b.png)
3) To each one I have added their respective dependencies. 
4) i changed the compilation action for the main library in to Library Project Zip, and the dependencies for EmbeddedReferenceJar. for each of the project.

5) Compile for generate respectives DLL files.
![image](https://user-images.githubusercontent.com/44584844/183521011-bbadf557-0d90-4ec4-be03-f3a7bd3e1f0e.png)
![image](https://user-images.githubusercontent.com/44584844/183521228-c72b5d43-c8a8-4910-a4c6-a8ced4fd55f1.png)

6) i created a new proyect for testing dll's but this not containt all clases. in this case  :plus-reader  is the ClassLibrary3.dll 
the first step is create an application clas that initialices the sdk and the card reader. whit the following comand 

ClipApi.init(this, new ClipPlusApi());

ClipApi is included on the PrimerBinding.dll, that initialices the sdk, 
CLipPlusApi() initialices the Card Reader. but the class inside the ClassLibrary3 is missing. like other clases

this are the classes inside AAR for plus-reader
![image](https://user-images.githubusercontent.com/44584844/183524078-e39a2111-d721-40b8-9384-d41143445d01.png)

this are the classes inside dll 

![image](https://user-images.githubusercontent.com/44584844/183524158-e534e3f5-c5c6-477d-862e-940a4b7842c1.png)

If you could guide me on what I'm doing wrong, how I could fix my mistake, or what approach I could take to make a correct Binding of the libraries.

I clarify that if I have been able to solve the processes that I need to carry out, through another type of solution, I have created a native android studio application that communicates with my MAUI application. But I would like to know if I can find any solution when creating a binding

THX

**Comment by jamesmontemagno** [comment]
The best place to ask this would be over in https://github.com/xamarin/xamarin-android, but it should be the same as https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/ 

also recently Kinfey did a video: https://www.youtube.com/watch?v=oibfI-ZsmzQ
