### ISSUE TITLE
Name property bug on Pixel device

### ISSUE THREAD

**Issue by 0nly1ken0bi** [dotnet-presentations/dotnet-maui-workshop#85]
I'm finding a very peculiar bug on the MainPage.xaml page particularly with the Name property in the CollectionView whereby Name="Baboon 1"  doesn't display the 1.  Also the Location="Africa and Asia" doesn't display correctly and it will only show [Africa and] and nothing else unless I insert a space after the word Asia.  

This appears to be a bug in both the Pixel 2 Q 10.0 - API 29 and the Pixel 5 API 33 emulators.  

The Location property is not a problem in the Pixel 5 but it has the same bug where the Name property doesn't display correctly i.e. Name="Baboon 1"

However, "Baboon 2", "Baboon 3", "Baboon 4"  Name properties etc.. all display their name's correctly just not the very first one i.e. "Baboon 1".

That said, the following DOES work on both the Pixel 2 and Pixel 5 using the # to denote the number:

```
<CollectionView>
        <CollectionView.ItemsSource>
            <x:Array Type="{x:Type model:Monkey}">
                <model:Monkey
                    **Name="Baboon #1"**
                    Image="https://raw.githubusercontent.com/jamesmontemagno/app-monkeys/master/baboon.jpg"
                    Location="Africa and Asia"/>
                <model:Monkey
                    **Name="Baboon #2"**
                    Image="https://raw.githubusercontent.com/jamesmontemagno/app-monkeys/master/baboon.jpg"
                    Location="Africa and Asia"/>
                <model:Monkey
                    **Name="Baboon #3"**
                    Image="https://raw.githubusercontent.com/jamesmontemagno/app-monkeys/master/baboon.jpg"
                    Location="Africa and Asia" />
                <model: Monkey
```

![Pixel 2 - API 29](https://user-images.githubusercontent.com/54916539/190702237-08184bde-5e01-4fe9-b11f-56903afffa6b.PNG)

![Pixel 5 - API 33](https://user-images.githubusercontent.com/54916539/190702735-7a779f31-dbf2-4083-8738-0dadf07a8634.PNG)

Not sure if this is where this issue goes.  Maybe someone else has experienced this as well?

**Comment by jamesmontemagno** [comment]
On this the "Name" is the key when you hardcode it in the list, so you will want those all to be unique.  It looks accurate to me in your screenshots....
