### ISSUE TITLE
Part 1 - input string was not in a correct format

### ISSUE THREAD

**Issue by Penny2704** [dotnet-presentations/dotnet-maui-workshop#93]
Hello, 

I'm watching the tutorial on YT but when I  try to build the solution for Android  I receive the following error on the string at line 1 in the MainPage.xaml:
[input string was not in a correct format]
![image](https://user-images.githubusercontent.com/109947130/200174574-3d1e91ee-8f7d-48cb-816f-71c0be2950ae.png)

I've compared the string with the video and I haven't found difference.
What could cause this problem?

Many thanks
Gaetano

**Comment by jamesmontemagno** [comment]
Hmmmm is there anything out in the input @Penny2704  with more information?

**Comment by Penny2704** [comment]
Hi @jamesmontemagno,
I upgraded to .net 7, deleted the entire project and followed the github guide step by step. The problem does not seem to recur and I have finished the second part as well.

Maybe I skipped some steps trying to follow from the yt guide.

Anyway thanks for the help
