### ISSUE TITLE
[Question] How to handle the specific index view within a ListView

### ISSUE THREAD

**Issue by Kumima** [dotnet-presentations/dotnet-maui-workshop#96]
```xml
<ListView ItemsSource="{Binding Monkeys}">
    <ListView.ItemTemplate>
        <DataTemplate>
            <ViewCell>
                <Label 
                       Text="{Binding Name}"
                       FontAttributes="Bold" />
            </ViewCell>
        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
```
For this kind of `ListView`, the controls within the `ListView` are templated. So how to get reference of a specific control? The selected item type is a `Monkey`, what if I wanna replace the `Label` into another control from code behind? It annoys me when I wanna realize the rename function using data binding, just like following picture. Or is there a better way to realize this situation?
![image](https://user-images.githubusercontent.com/93973732/203491845-48a60446-e411-4a75-b03d-bc05f6a11cd3.png)

**Comment by jamesmontemagno** [comment]
You most likely want to use Data Template selectors: https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/datatemplate?view=net-maui-7.0#create-a-datatemplateselector
